/* ─────────────────────────────────────────────
   indway 
───────────────────────────────────────────── */
window.INDWAY_DATA = {
  /* ── PROFILE ────────────────────────────── */
  profile: {
    title: "AI-driven Solution Architect",
    bio: {
      id: "Membangun sistem cerdas dan solusi digital berdampak tinggi. Fokus pada integrasi AI, automasi, dan arsitektur produk yang skalabel.",
      en: "Crafting intelligent systems and high-impact digital solutions. Focused on AI integration, automation, and scalable product architecture.",
    },
    services: [
      { id: "ser_ai", label: "AI Integration" },
      { id: "ser_arch", label: "System Architecture" },
      { id: "ser_web", label: "Full-stack Dev" },
      { id: "ser_auto", label: "Automation" },
    ],
    stack: ["Node.js", "Python", "React", "Docker", "PyTorch", "Git"],
    experience: "7+ years building digital products",
    availability: "Open to Remote / Freelance",
  },

  /* ── RATES ──────────────────────────────── */
  rates: {
    id: { symbol: "Rp", amount: "750.000", unit: "jam",  note: "(perkiraan, tergantung proyek)" },
    en: { symbol: "$",  amount: "45",       unit: "hr",   note: "(negotiable)" },
    ms: { symbol: "RM", amount: "210",      unit: "jam",  note: "(boleh dirunding)" },
    ar: { symbol: "$",  amount: "45",       unit: "hr",   note: "(قابل للتفاوض)" },
  },

  /* ── I18N ────────────────────────────────── */
  i18n: {
    id: {
      tagline:               "AI-driven Solution Architect",
      greeting:              "hai,",
      here:                  "disini.",
      contact_pre:           "tertarik lebih lanjut? email saya di",
      rate_pre:              "open to collaboration · mulai dari",
      sec_products:          "produk dari lab",
      sec_web:               "web yang dikelola",
      sec_side:              "side project",
      sec_themes:            "theme web",
      sec_cyber:             "cybersecurity tools",
      sec_find:              "find me",
      also_see:              "lihat juga",
      mobile_ver:            "versi mobile",
      showcase_hint:         "hover produk untuk preview →",
      modal_visit:           "kunjungi →",
      modal_status_active:   "aktif",
      modal_status_wip:      "dalam pengerjaan",
      modal_status_archived: "arsip",
    },
    en: {
      tagline:               "AI-driven Solution Architect",
      greeting:              "hey,",
      here:                  "i'm here.",
      contact_pre:           "interested? reach me at",
      rate_pre:              "open to collaboration · starting at",
      sec_products:          "products from the lab",
      sec_web:               "managed websites",
      sec_side:              "side projects",
      sec_themes:            "web themes",
      sec_cyber:             "cybersecurity tools",
      sec_find:              "find me",
      also_see:              "also check",
      mobile_ver:            "mobile version",
      showcase_hint:         "hover a product to preview →",
      modal_visit:           "visit →",
      modal_status_active:   "active",
      modal_status_wip:      "in progress",
      modal_status_archived: "archived",
    },
    ms: {
      tagline:               "AI-driven Solution Architect",
      greeting:              "hai,",
      here:                  "saya disini.",
      contact_pre:           "berminat? emel saya di",
      rate_pre:              "terbuka untuk kerjasama · bermula",
      sec_products:          "produk dari lab",
      sec_web:               "laman web diurus",
      sec_side:              "projek sampingan",
      sec_themes:            "tema web",
      sec_cyber:             "alat keselamatan siber",
      sec_find:              "hubungi saya",
      also_see:              "lihat juga",
      mobile_ver:            "versi mudah alih",
      showcase_hint:         "hover produk untuk pratonton →",
      modal_visit:           "lawati →",
      modal_status_active:   "aktif",
      modal_status_wip:      "dalam pembangunan",
      modal_status_archived: "arkib",
    },
    ar: {
      tagline:               "أدوات من المختبر",
      greeting:              "مرحباً،",
      here:                  "أنا هنا.",
      contact_pre:           "مهتم؟ راسلني على",
      rate_pre:              "متاح للتعاون · يبدأ من",
      sec_products:          "منتجات المختبر",
      sec_web:               "المواقع المدارة",
      sec_side:              "مشاريع جانبية",
      sec_themes:            "قوالب ويب",
      sec_cyber:             "أدوات الأمن السيبراني",
      sec_find:              "تواصل معي",
      also_see:              "شاهد أيضاً",
      mobile_ver:            "النسخة المحمولة",
      showcase_hint:         "← مرر فوق منتج للمعاينة",
      modal_visit:           "زيارة →",
      modal_status_active:   "نشط",
      modal_status_wip:      "قيد التطوير",
      modal_status_archived: "أرشيف",
    },
  },

  /* ── PRODUCTS ────────────────────────────── */
  products: [
    {
      name: "ViGen",
      category: "ai · video",
      status: "active",
      desc: {
        id: "Video Generator dengan AI",
        en: "Video Generator With AI",
        ms: "Penjana Video Dengan AI",
        ar: "مولّد فيديو بالذكاء الاصطناعي",
      },
      detail: {
        id: "Tool untuk membuat video otomatis dari teks atau data menggunakan model AI. Cocok untuk konten sosial media, presentasi, dan marketing.",
        en: "A tool for automatically generating videos from text or data using AI models. Great for social media content, presentations, and marketing.",
        ms: "Alat untuk menjana video secara automatik daripada teks atau data menggunakan model AI.",
        ar: "أداة لإنشاء مقاطع فيديو تلقائياً من النصوص أو البيانات باستخدام نماذج الذكاء الاصطناعي.",
      },
      tags: ["AI", "Video", "Generator"],
      url: null,
      media: { type: "img", src: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&q=80" },
      subs: [],
    },
    {
      name: "GenSu",
      category: "ai · document",
      status: "active",
      desc: {
        id: "Si Pembuat Surat",
        en: "Letter & Document Generator",
        ms: "Penjana Surat & Dokumen",
        ar: "منشئ الرسائل والوثائق",
      },
      detail: {
        id: "Generator dokumen dan surat resmi berbasis AI. Dari surat lamaran kerja, proposal, kontrak, hingga laporan — cukup isi template, AI yang tulis.",
        en: "AI-based formal letter and document generator. From job applications, proposals, contracts to reports — just fill in the template, AI does the writing.",
        ms: "Penjana surat rasmi dan dokumen berasaskan AI. Daripada surat lamaran, cadangan, kontrak hingga laporan.",
        ar: "مولّد وثائق ورسائل رسمية بالذكاء الاصطناعي. من طلبات العمل والمقترحات إلى العقود والتقارير.",
      },
      tags: ["AI", "Document", "Automation"],
      url: null,
      media: { type: "img", src: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=1200&q=80" },
      subs: [],
    },
    {
      name: "Content Intelligence",
      category: "ai · content",
      status: "wip",
      desc: {
        id: "Pembuat Konten Berdasarkan Insight",
        en: "Insight-Based Content Generator",
        ms: "Penjana Kandungan Berasaskan Insight",
        ar: "إنشاء محتوى مبني على البيانات",
      },
      detail: {
        id: "Platform yang menganalisis tren, data audiens, dan kompetitor untuk menghasilkan konten yang relevan dan berdampak tinggi.",
        en: "A platform that analyzes trends, audience data, and competitors to generate relevant, high-impact content.",
        ms: "Platform yang menganalisis trend, data audiens dan pesaing untuk menghasilkan kandungan yang relevan.",
        ar: "منصة تحلل الاتجاهات وبيانات الجمهور والمنافسين لإنتاج محتوى ذي تأثير عالٍ.",
      },
      tags: ["AI", "Content", "Analytics"],
      url: null,
      media: { type: "img", src: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80" },
      subs: [],
    },
    {
      name: "Indexer",
      category: "seo · automation",
      status: "active",
      desc: {
        id: "Otomatis Indexing Website",
        en: "Automatic Website Indexer",
        ms: "Pengindeks Laman Web Automatik",
        ar: "أداة فهرسة المواقع التلقائية",
      },
      detail: {
        id: "Tool untuk mengotomasi proses indexing halaman website ke mesin pencari. Submit sitemap, ping URL, dan monitor status indexing dalam satu dashboard.",
        en: "A tool to automate the process of indexing website pages to search engines. Submit sitemaps, ping URLs, and monitor indexing status in one dashboard.",
        ms: "Alat untuk mengautomasikan pengindeksan halaman web ke enjin carian dalam satu papan pemuka.",
        ar: "أداة لأتمتة عملية فهرسة صفحات المواقع في محركات البحث. إرسال الخرائط وتتبع الحالة.",
      },
      tags: ["SEO", "Automation", "Indexing"],
      url: null,
      media: { type: "img", src: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&q=80" },
      subs: [],
    },
    {
      name: "1826d",
      category: "productivity · journal",
      status: "active",
      desc: {
        id: "Catatan Perjalanan Hidup",
        en: "Life Journey Journal",
        ms: "Jurnal Perjalanan Hidup",
        ar: "يوميات رحلة الحياة",
      },
      detail: {
        id: "Journal digital pribadi yang aman dan terenkripsi. 1826 hari = 5 tahun perjalanan hidup. Simpan momen, pikiran, dan refleksi harian dengan enkripsi AES-256.",
        en: "A secure, encrypted personal digital journal. 1826 days = 5 years of life's journey. Store moments, thoughts, and daily reflections with AES-256 encryption.",
        ms: "Jurnal digital peribadi yang selamat dan disulitkan. 1826 hari = 5 tahun perjalanan hidup. Simpan kenangan dengan penyulitan AES-256.",
        ar: "يوميات رقمية شخصية آمنة ومشفرة. ١٨٢٦ يوماً = ٥ سنوات من رحلة الحياة. تشفير AES-256.",
      },
      tags: ["Journal", "Encrypted", "Offline"],
      url: null,
      media: { type: "img", src: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=1200&q=80" },
      subs: [],
    },
    {
      name: "lihatmami",
      category: "art · steganography",
      status: "active",
      desc: {
        id: "Steganografi · seni @kodekeras.jpg",
        en: "Steganography · art @kodekeras.jpg",
        ms: "Steganografi · seni @kodekeras.jpg",
        ar: "إخفاء البيانات · @kodekeras.jpg",
      },
      detail: {
        id: "Eksperimen menyembunyikan data di dalam gambar seni. Kolaborasi antara kode dan estetika visual dari akun @kodekeras.jpg.",
        en: "An experiment hiding data inside art images. A collaboration between code and visual aesthetics from @kodekeras.jpg.",
        ms: "Eksperimen menyembunyikan data dalam gambar seni daripada akaun @kodekeras.jpg.",
        ar: "تجربة إخفاء البيانات داخل صور فنية. تعاون بين الكود والجماليات البصرية.",
      },
      tags: ["Art", "Steganography", "Creative"],
      url: "https://instagram.com/kodekeras.jpg",
      media: { type: "img", src: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=1200&q=80" },
      subs: [],
    },
    {
      name: "jadicms",
      category: "cms · git",
      status: "active",
      desc: {
        id: "Git Based Content Hub & Media Management",
        en: "Git-Based Content Hub & Media Management",
        ms: "Hab Kandungan Berasaskan Git",
        ar: "إدارة المحتوى والوسائط عبر Git",
      },
      detail: {
        id: "CMS berbasis Git untuk mengelola konten dan media. Tidak perlu database — semua tersimpan di repository. Cocok untuk tim kecil dan developer.",
        en: "A Git-based CMS for managing content and media. No database needed — everything stored in a repository. Great for small teams and developers.",
        ms: "CMS berasaskan Git untuk mengurus kandungan dan media. Tiada pangkalan data diperlukan.",
        ar: "نظام إدارة محتوى مبني على Git. لا قاعدة بيانات مطلوبة — كل شيء مخزن في المستودع.",
      },
      tags: ["CMS", "Git", "No-DB"],
      url: null,
      media: { type: "img", src: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=1200&q=80" },
      subs: [],
    },
  ],

  /* ── WEBSITES ────────────────────────────── */
  websites: [
    {
      name: "schlab.id",
      url: "https://schlab.id",
      category: "education",
      status: "active",
      desc: {
        id: "School as Living Lab",
        en: "School as Living Lab",
        ms: "Sekolah sebagai Makmal Hidup",
        ar: "المدرسة كمختبر حي",
      },
      detail: {
        id: "Platform untuk sekolah yang ingin menjadi laboratorium hidup — tempat belajar, bereksperimen, dan berinovasi bersama siswa.",
        en: "A platform for schools that want to become living labs — a place to learn, experiment, and innovate together with students.",
        ms: "Platform untuk sekolah yang ingin menjadi makmal hidup — tempat belajar dan berinovasi bersama pelajar.",
        ar: "منصة للمدارس التي تريد أن تصبح مختبرات حية — مكان للتعلم والتجريب والابتكار.",
      },
      tags: ["Education", "School", "Innovation"],
      media: null,
      subs: [],
    },
    {
      name: "jadi.pw",
      url: "https://jadi.pw",
      category: "marketplace · tools",
      status: "active",
      desc: {
        id: "Digital Product Marketplace & Productivity Tools",
        en: "Digital Product Marketplace & Productivity Tools",
        ms: "Pasaran Produk Digital & Alat Produktiviti",
        ar: "سوق المنتجات الرقمية",
      },
      detail: {
        id: "Marketplace untuk produk digital dan tools produktivitas. Jual template, tools, dan konten digital dengan sistem pembayaran terintegrasi.",
        en: "A marketplace for digital products and productivity tools. Sell templates, tools, and digital content with an integrated payment system.",
        ms: "Pasaran untuk produk digital dan alat produktiviti dengan sistem pembayaran bersepadu.",
        ar: "سوق للمنتجات الرقمية وأدوات الإنتاجية مع نظام دفع متكامل.",
      },
      tags: ["Marketplace", "Digital", "Productivity"],
      media: null,
      subs: [
        {
          name: "kampung.jadi.pw",
          url: "https://kampung.jadi.pw",
          desc: {
            id: "Digitalisasi Warga Desa",
            en: "Village Community Digitalization",
            ms: "Pendigitalan Komuniti Kampung",
            ar: "رقمنة المجتمعات القروية",
          },
        },
        {
          name: "refleksi.jadi.pw",
          url: "https://refleksi.jadi.pw",
          desc: {
            id: "Ruang Introspeksi Diri",
            en: "Self-Reflection Space",
            ms: "Ruang Refleksi Diri",
            ar: "فضاء التأمل الذاتي",
          },
        },
      ],
    },
    {
      name: "KodeKeras Society",
      url: "https://society.kodekeras.my.id",
      category: "community · productivity",
      status: "active",
      desc: {
        id: "Productivity Tracking",
        en: "Productivity Tracking",
        ms: "Penjejak Produktiviti",
        ar: "تتبع الإنتاجية",
      },
      detail: {
        id: "Komunitas produktivitas untuk developer dan kreator. Track progress, berbagi insight, dan saling mendorong mencapai target.",
        en: "A productivity community for developers and creators. Track progress, share insights, and motivate each other to reach goals.",
        ms: "Komuniti produktiviti untuk pembangun dan pencipta. Jejak kemajuan dan berkongsi wawasan.",
        ar: "مجتمع الإنتاجية للمطورين والمبدعين. تتبع التقدم وتبادل الأفكار.",
      },
      tags: ["Community", "Productivity", "Developer"],
      media: null,
      subs: [],
    },
  ],

  /* ── SIDE PROJECTS ───────────────────────── */
  side: [
    {
      name: "monstroku",
      url: "https://instagram.com/monstroku",
      category: "universe · family",
      status: "active",
      desc: {
        id: "universe project · imajinasi dan kolaborasi ayah dan anak",
        en: "universe project · imagination & father-son collaboration",
        ms: "projek semesta · imaginasi & kolaborasi ayah dan anak",
        ar: "مشروع كوني · تعاون بين الأب والابن",
      },
      detail: {
        id: "Proyek semesta — eksplorasi imajinasi bersama anak. Karakter, dunia, dan cerita yang dibangun bersama sebagai warisan kreativitas keluarga.",
        en: "A universe project — exploring imagination together with a child. Characters, worlds, and stories built together as a family creative legacy.",
        ms: "Projek semesta — penerokaan imaginasi bersama anak. Watak, dunia dan cerita yang dibina bersama.",
        ar: "مشروع كوني — استكشاف الخيال مع الطفل. شخصيات وعوالم وقصص بُنيت معاً كإرث إبداعي عائلي.",
      },
      tags: ["Family", "Creative", "Universe"],
      media: null,
      subs: [],
    },
  ],

  /* ── WEB THEMES ──────────────────────────── */
  themes: [
    {
      name: "./pentest",
      category: "web theme · dark",
      status: "active",
      desc: {
        id: "blog template for hacker notes",
        en: "blog template for hacker notes",
        ms: "templat blog penggodam",
        ar: "قالب مدونة للهاكر",
      },
      detail: {
        id: "Template blog dengan estetika terminal dan hacker. Warna gelap, font monospace, cocok untuk catatan keamanan siber atau dev notes.",
        en: "A blog template with terminal and hacker aesthetics. Dark colors, monospace font, perfect for cybersecurity notes or dev notes.",
        ms: "Templat blog dengan estetik terminal. Warna gelap, fon monospace, sesuai untuk nota keselamatan siber.",
        ar: "قالب مدونة بأسلوب المحطة الطرفية. ألوان داكنة وخط أحادي المسافة — مثالي لملاحظات الأمن السيبراني.",
      },
      tags: ["Dark Theme", "Blog", "Terminal"],
      url: null,
      media: { type: "img", src: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=1200&q=80" },
      subs: [],
    },
    {
      name: "Sekolahku",
      category: "web theme · education",
      status: "active",
      desc: {
        id: "web template for school",
        en: "web template for school",
        ms: "templat web sekolah",
        ar: "قالب موقع للمدارس",
      },
      detail: {
        id: "Template website sekolah yang bersih, modern, dan mudah dikustomisasi. Tersedia halaman profil, akademik, berita, dan PPDB.",
        en: "A clean, modern, and easily customizable school website template. Includes profile, academic, news, and enrollment pages.",
        ms: "Templat laman web sekolah yang bersih dan moden. Termasuk halaman profil, akademik, berita dan pendaftaran.",
        ar: "قالب موقع مدرسي نظيف وحديث وقابل للتخصيص. يشمل صفحات الملف الشخصي والأكاديمي والأخبار.",
      },
      tags: ["Education", "Clean", "Template"],
      url: null,
      media: { type: "img", src: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1200&q=80" },
      subs: [],
    },
  ],

  /* ── CYBERSECURITY ───────────────────────── */
  cyber: [
    {
      name: "BeterCut",
      category: "network · tool",
      status: "archived",
      desc: {
        id: "Alternatif Netcut",
        en: "Netcut Alternative",
        ms: "Alternatif Netcut",
        ar: "بديل Netcut",
      },
      detail: {
        id: "Tool manajemen jaringan lokal. Alternatif Netcut dengan fitur monitoring dan kontrol koneksi perangkat di jaringan yang sama.",
        en: "A local network management tool. A Netcut alternative with monitoring and connection control for devices on the same network.",
        ms: "Alat pengurusan rangkaian tempatan. Alternatif Netcut dengan pemantauan dan kawalan sambungan.",
        ar: "أداة لإدارة الشبكة المحلية. بديل لـ Netcut مع ميزات المراقبة والتحكم في الاتصال.",
      },
      tags: ["Network", "LAN", "Monitor"],
      url: null,
      media: null,
      subs: [],
    },
    {
      name: "Rp",
      category: "security · research",
      status: "archived",
      desc: {
        id: "a spying tools",
        en: "a spying tool",
        ms: "alat pengintipan",
        ar: "أداة تجسس",
      },
      detail: {
        id: "Tool eksperimen untuk keperluan riset keamanan. Dibuat untuk memahami mekanisme spyware dan cara melindungi diri darinya.",
        en: "An experimental tool for security research. Built to understand spyware mechanisms and how to protect against them.",
        ms: "Alat eksperimen untuk penyelidikan keselamatan. Dibuat untuk memahami mekanisme perisian perisik.",
        ar: "أداة تجريبية لأغراض البحث الأمني. مُبنية لفهم آليات برامج التجسس والحماية منها.",
      },
      tags: ["Research", "Security", "Experimental"],
      url: null,
      media: null,
      subs: [],
    },
  ],

  /* ── SOCIALS ─────────────────────────────── */
  socials: [
    { label: "email",              url: "mailto:indway@duck.com" },
    { label: "diary",              url: "/diary/" },
    { label: "follow @indthatway", url: "https://instagram.com/indthatway" },
    { label: "desktop",            url: "https://kodekeras.my.id" },
  ],
};
